package com.wsk.spark.stream

import org.apache.spark.SparkConf
import org.apache.spark.HashPartitioner
import org.apache.spark.streaming._

/**
  * updateStateByKey Transformations,实现夸批次的wordcount
  *
  * 1)updatestatebykey虽然能实现夸批次的处理，但是checkpoin会生成很多小文件
  *   ，生产上，最合理的方式弃用checkpoint，直接写入DB
  * 2）生产上Spark是尽量尽量不使用CheckPoint的，垃圾，深坑，生成太多的小文件了。
  */
object UpdateStateBykeyTfTest {
  def main(args: Array[String]) {

    ///函数的返回类型是Some(Int)，因为preValue的类型就是Option
    ///函数的功能是将当前时间间隔内产生的Key的value集合的和，与之前的值相加
    val updateFunc = (values: Seq[Int], preValue: Option[Int]) => {
      val currentCount = values.sum
      val previousCount = preValue.getOrElse(0)
      Some(currentCount + previousCount)
    }

    ///入参是三元组遍历器，三个元组分别表示Key、当前时间间隔内产生的对应于Key的Value集合、上一个时间点的状态
    ///newUpdateFunc的返回值要求是iterator[(String,Int)]类型的
    val newUpdateFunc = (iterator: Iterator[(String, Seq[Int], Option[Int])]) => {
      ///对每个Key调用updateFunc函数(入参是当前时间间隔内产生的对应于Key的Value集合、上一个时间点的状态）得到最新状态
      ///然后将最新状态映射为Key和最新状态
      iterator.flatMap(t => updateFunc(t._2, t._3).map(s => (t._1, s)))
    }

    val sparkConf = new SparkConf()
      .setAppName("StatefulNetworkWordCount")
      .setMaster("local[3]")
    // Create the context with a 5 second batch size
    val ssc = new StreamingContext(sparkConf, Seconds(5))
    ssc.checkpoint(".")

    // Initial RDD input to updateStateByKey
    val initialRDD = ssc.sparkContext.parallelize(List(("hello", 1), ("world", 1)))
    // Create a ReceiverInputDStream on target ip:port and count the
    // words in input stream of \n delimited test (eg. generated by 'nc')
    val lines = ssc.socketTextStream("192.168.76.120", 1314)
    val words = lines.flatMap(_.split(" "))
    val wordDstream = words.map(x => (x, 1)).reduceByKey(_+_)

    // Update the cumulative count using updateStateByKey
    // This will give a Dstream made of state (which is the cumulative count of the words)
    //注意updateStateByKey的四个参数，第一个参数是状态更新函数
//    val stateDstream = wordDstream.updateStateByKey[Int](newUpdateFunc,
//      new HashPartitioner(ssc.sparkContext.defaultParallelism), true, initialRDD)
    val stateDstream = wordDstream.updateStateByKey(updateFunc)

    stateDstream.print()
    ssc.start()
    ssc.awaitTermination()
  }
}